#!/bin/sh
# shellcheck disable=SC2139

# Prefix sudo automatically
for command in mount umount updatedb timeshift powertop; do
	alias $command="sudo $command"
done; unset command

# General
alias \
  g='git' \
  t='tmux' \
  p='yay' \
  v='$EDITOR' \
  m='mpv --shuffle --no-osc --term-osd-bar --save-position-on-quit --geometry=50%x50%' \
  free='free -h' \
  curl="curl -sL" \
  wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"' \

# Colorize commands
alias \
  grep='grep --color=auto' \
  diff='diff --color=auto' \
  cal='cal -m --color=auto' \

# File manager
alias \
  cp='cp -iv' \
  mv='mv -iv' \
  rm='rm -vI' \
  df='df -h' \
  dl='trash-put' \
  unmount='udiskie-umount -d' \

# ls
alias \
  ls='lsd --group-dirs first' \
  sl='lsd --group-dirs first' \
  l='lsd --blocks permission,links,user,size,date,name --date relative -l' \
  la='ls -A' \
  lla='l -A' \
  ld='(setopt +o nomatch ; lsd --directory-only */ 2> /dev/null ; true)' \
  lt='ls --tree' \
  ltd='(setopt +o nomatch ; lsd --tree --directory-only */ 2> /dev/null)' \

# z / cd
alias \
  zz='cd - 1> /dev/null && ld' \
  ..='cd .. && ld' \
  ...='cd ../.. && ld' \
  ....='cd ../../.. && ld' \
  fz='cd "$(find -type d | fzf)" && ld' \

z() { __zoxide_z "$@" && ld ; }
zi() { __zoxide_zi "$@" && ld ; }

# List all installed packages by size
alias pkgs-size="pacman -Qi | grep -E '^(Name|Installed)' | cut -f2 -d':' | paste - - | column -t | sort -nrk 2 | grep MiB"

# Dotfiles
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias dot=dotbare

# Notes
alias \
  n="(cd $NOTES_DIR; nd 2>/dev/null; $EDITOR $NOTES_DIR/notes.md; ne)" \
  ne="$NOTES_DIR/notes.sh encrypt" \
  nd="$NOTES_DIR/notes.sh decrypt" \

# Open temporary file scratch pad and copy saved content to clipboard on exit
alias tmpv='FILE=$(mktemp /tmp/tmp.XXXXX.md) && $EDITOR $FILE && clip.exe < $FILE && "rm" $FILE'

# Open shell in a temporary dir
alias tmpsh='(DIR=$(mktemp -d) && cd $DIR && $SHELL && "rm" -rf $DIR)'

# Fuzzy select and copy command from history
alias h='history 1 | cut -c 8- | uniq | fzf -0 --tac | xclip -r -sel -c'

# Download music from youtube
alias ytm-dlp='yt-dlp -x --audio-quality 0 --embed-metadata --embed-thumbnail'

# Search channel/playlist
yts_dlp() {
  yt-dlp --no-warnings \
    --get-filename -o "https://youtu.be/%(id)s: %(title)s" \
    --match-title "$2" "$1"
}

# cheat.sh
tldr() { curl "cheat.sh/$1" ; }

# Get External IP
alias getip='curl -s https://ipinfo.io/json | jq'
