#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

while read file
do
    case "$1" in
    "w") xwallpaper --zoom "$file" & ;;
    "r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
    "f")
		convert -flop "$file" "$file" ;;
    "y")
		echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file path copied to clipboard" & ;;
    "Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") path copied to clipboard" & ;;
    "c")
        xclip -selection clipboard "$file" -t image/png &&
		notify-send "$(readlink -f "$file") copied to clipboard" & ;;
    "d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
    "g")    setsid -f gimp "$file" ;;
    esac
done
