#!/bin/sh

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Fix small dwm bar in HiDPI displays (sometimes xresources does not work)
xrandr --dpi 125 &

# Set random wallpaper
wallpapers="$HOME/main/library/pictures/wallpapers/"
picture="$(find "$wallpapers" -maxdepth 1 -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -type f | shuf -n 1)"
xwallpaper --zoom "$picture" &

(sleep 2; xmodmap "$HOME/.config/xmodmap/Xmodmap") &
xrdb -merge "$HOME/.config/x11/xresources" &
setxkbmap us,ru -option "compose:ralt" &
slstatus &
clipmenud &
sxhkd &
remaps &
unclutter &
warp-cli connect &
picom &
redshift -l 50:30 &
battery-daemon &
(sleep 2; warpd) &

exec dwm
