#!/bin/sh

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set random wallpaper
xwallpaper --zoom "$(find "$WALLPAPERS" -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -type f | shuf -n 1)" &

xrdb -merge "$HOME/.config/x11/xresources"
setxkbmap us,ru -option grp:alt_shift_toggle -option "compose:ralt" &
slstatus &
clipmenud &
sxhkd &
remaps &
unclutter &
picom &
redshift -l 50:30 &
battery-daemon &
syncthing-check &
(sleep 2; warpd) &

exec dwm
