#!/bin/sh

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set random wallpaper
feh --no-fehbg --bg-fill "$(find "$WALLPAPERS" -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -type f | shuf -n 1)" &

# dwm bar
while true; do
  xprop -root -set WM_NAME "$(date '+%a %b %d %H:%M ')"
  sleep 2
done &

xrdb -merge "$HOME/.config/x11/xresources"
setxkbmap us,ua -option grp:alt_shift_toggle,compose:ralt &
clipmenud &
sxhkd &
remaps &
unclutter &
picom &
playerctld daemon &
udiskie &
redshift -l 50:30 &
(sleep 2; warpd) &
notify-battery &
notify-syncthing &
git-backup &
volumeicon &
(sleep 1; cbatticon -n -l 30 -x dmenu-powermenu) &
(sleep 2; nm-applet) &
(sleep 3; telegram-desktop -startintray) &

exec dwm
