#!/bin/sh

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

print_help()
{
  printf %s "\
w: set as the wallpaper
r: rotate +90
R: rotate -90
f: flop
y: copy filepath
Y: copy filename
c: copy to clipboard
d: delete
e: open in the editor
s: share
"
}

while read -r file; do
  file="$(realpath -- "$file")"
  filename="$(basename -- "$file")"
  case "$1" in
    "h")
      notify-send "Key handler" "$(print_help)"
      ;;
    "w")
      feh --no-fehgb --bg-fill "$file" ;;
    "r")
      convert -rotate 90 "$file" "$file" ;;
    "R")
      convert -rotate -90 "$file" "$file" ;;
    "f")
      convert -flop "$file" "$file" ;;
    "y")
      printf "%s" "$file" | xclip -selection clipboard
      notify-send "$file path copied to clipboard"
      ;;
    "Y")
      printf "%s" "$filename" | xclip -selection clipboard
      notify-send "$filename filename copied to clipboard"
      ;;
    "c")
      xclip -selection clipboard "$file" -t image/png
      notify-send "$filename copied to clipboard"
      ;;
    "d")
      choice="$(printf "No\\nYes" | dmenu -i -p "Really delete $filename?")"
      [ "$choice" = "Yes" ] && trash-put "$file" && notify-send "$filename deleted."
      ;;
    "e") setsid -f gimp "$file" ;;
    "s")
      share "$file"
      notify-send "$filename shared to $(xclip -o -sel clip)"
      ;;
  esac
done
