matches:

  # General

  - triggers: [":date", ":Date"]
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - triggers: [":time", ":Time"]
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - triggers: [":stamp", ":Stamp"]
    replace: "{{stampdate}}"
    vars:
      - name: stampdate
        type: date
        params:
          format: "%Y%m%d%H%M%S"

  - triggers: [":shrug", ":Shrug"]
    replace: "¯\\_(ツ)_/¯"

  - triggers: [":email", ":Email"]
    replace: "vasyl.tyshchuk.xyz@gmail.com"

  - triggers: [":github", ":Github"]
    replace: "https://github.com/basilioss"

  # Markdown

  - triggers: [":ttt", ":Ttt"]
    replace: "- [ ] "

  - triggers: [":mdlink", ":Mdlink"]
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Shell

  - triggers: [":sed", ":Sed"]
    replace: "| sed 's/$|$//g' "

  - triggers: [":foreach", ":Foreach"]
    replace: "for i in $|$; do ; done"

  - triggers: [":bak", ":Bak"]
    label: "Create a backup (cp file.txt{,.bak})"
    replace: "{,.bak}"

  - triggers: [":null", ":Null"]
    label: "Redirect errors to /dev/null"
    replace: "2> /dev/null"

  - triggers: [":nohup", ":Nohup"]
    label: "Run a command in the background even after the terminal is terminated"
    replace: "nohup $|$ &>/dev/null &"
